import Link from "next/link";

export const metadata = {
  title: "Terms of Service — DEFRAG",
  description: "Terms of service for the DEFRAG relational intelligence platform.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#09090b] text-white font-sans antialiased">
      <div className="mx-auto max-w-[720px] px-6 md:px-10 py-24 md:py-32">
        <Link
          href="/"
          className="inline-block text-[14px] font-bold tracking-[0.2em] text-white/90 uppercase mb-16"
        >
          DEFRAG
        </Link>

        <h1 className="text-[36px] md:text-[48px] font-bold tracking-[-0.03em] leading-[1.05] text-white mb-4">
          Terms of Service
        </h1>
        <p className="text-[14px] text-white/30 mb-12">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>

        <div className="space-y-10 text-[15px] text-white/55 leading-[1.85]">
          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">1. Acceptance</h2>
            <p>
              By accessing or using DEFRAG (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service. We may update these terms at any time. Continued use
              constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">2. The Service</h2>
            <p>
              DEFRAG is a relational intelligence platform. It uses birth data and user-provided context to generate
              insights about interpersonal dynamics. DEFRAG is not a licensed therapy, counseling, or medical service.
              Outputs are generated by AI and should not be treated as professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">3. Accounts</h2>
            <p>
              You must provide accurate information when creating an account. You are responsible for maintaining the
              security of your account credentials. One person per account. You must be at least 16 years old to use
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">4. Privacy &amp; Data</h2>
            <p>
              We take privacy seriously. Your birth data and relationship context are stored securely and never shared
              with third parties for advertising. You can delete your data at any time from Settings. We use Supabase
              for authentication and data storage with row-level security enabled. See our principles page for more.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">5. Subscriptions &amp; Billing</h2>
            <p>
              DEFRAG offers Free, Solo ($19/month), and Team ($33/month) plans. Paid subscriptions are billed monthly
              through Stripe. You may cancel at any time from your account settings. Cancellation takes effect at the
              end of the current billing period. No refunds for partial months.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">6. Acceptable Use</h2>
            <p>
              You agree not to: (a) use the Service to harass, stalk, or harm others; (b) share another person&rsquo;s
              private information without consent; (c) attempt to reverse-engineer or exploit the Service; (d) use
              automated tools to scrape or access the Service beyond normal use.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">7. Limitation of Liability</h2>
            <p>
              DEFRAG is provided &ldquo;as is&rdquo; without warranty of any kind. We are not liable for any decisions
              you make based on the Service&rsquo;s outputs. Our total liability is limited to the amount you paid in
              the 12 months preceding any claim.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white/85 mb-3">8. Contact</h2>
            <p>
              Questions about these terms? Contact us at{" "}
              <a href="mailto:info@defrag.app" className="text-white/70 underline hover:text-white/90 transition-colors">
                info@defrag.app
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/[0.06]">
          <Link href="/" className="text-[12px] uppercase tracking-[0.12em] text-white/25 hover:text-white/45 transition-colors duration-200">
            Back to home
          </Link>
        </div>
      </div>
    </main>
  );
}
